version: '3.7'

services:
  main-service:
    container_name: main-service
    build:
      context: ./main-service
      dockerfile: ./main-service.Dockerfile
      args:
        - MONGO_DB_NAME=${MONGO_DB_NAME}
        - MONGO_DB_ROOT_USERNAME=${MONGO_DB_ROOT_USERNAME}
        - MONGO_DB_ROOT_PASSWORD=${MONGO_DB_ROOT_PASSWORD}
        - MONGO_DB_PORT=${MONGO_DB_PORT}
        - MONGO_DB_HOST=${MONGO_DB_HOST}
        - MAIN_SERVICE_PORT=${MAIN_SERVICE_PORT}
        - MAIN_SERVICE_JWT_PRIVATE_KEY=${MAIN_SERVICE_JWT_PRIVATE_KEY}
        - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    command: sh -c "/wait && npm run db:reset && npm start"
    ports:
      - ${MAIN_SERVICE_PORT}:${MAIN_SERVICE_PORT}
    environment:
      WAIT_HOSTS: mongo:${MONGO_DB_PORT}

  mongo:
    container_name: mongo
    image: 'mongo:latest'
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASSWORD}
    volumes:
      - mongo_db_data:/data/db

volumes:
  mongo_db_data: